### ISSUE TITLE
Unsupported / invalid stamp generated?

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-website#28]
Hi @jedisct1,

Recently I tried to generate some DNS stamps for certain DNS-over-TLS services using the [Online DNS Stamp calculator on the website](https://dnscrypt.info/stamps), for example, [RethinkDNS(hostname: `max.rethinkdns.com`)](https://rethinkdns.com/configure), but when I put the stamp in DNSCrypt proxy config(`dnscrypt-proxy.toml`) like this:


```toml
  [static.'rethinkdns']                                                                                                                                                                                                                     
  stamp = 'sdns://AwAAAAAAAAAAAAASbWF4LnJldGhpbmtkbnMuY29t'
```

or this:

```toml
  [static.'rethinkdns']                                                                                                                                                                                                                     
  stamp = 'sdns://AwAAAAAAAAAADjIxMy4xODguMjE4Ljg1ABJtYXgucmV0aGlua2Rucy5jb20' 
```

A fatal error just came up:
```
[2022-01-31 16:13:29] [FATAL] Stamp error for the static [rethinkdns] definition: [Unsupported stamp version or protocol]
```

The version of DNSCrypt proxy is the latest v2.1.1, do you have any idea or suggestions on what might be wrong Thanks a lot!
